apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangway
  labels:
    app: gangway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangway
  template:
    metadata:
      labels:
        app: gangway
    spec:
      containers:
      - name: gangway
        image: gcr.io/heptio-images/gangway:v3.2.0
        imagePullPolicy: Always
        command: ["gangway", "-config", "/gangway/gangway.yml"]
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 60
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: gangway
          mountPath: /gangway/
      volumes:
      - name: gangway
        secret:
          secretName: gangway
---
kind: Service
apiVersion: v1
metadata:
  name: gangway-svc
  labels:
    app: gangway
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: gangway
