# TODO add a backup for the current configmap with date-time, to be able to restore

- name: Dump kubeadm-config
  ansible.builtin.shell: |
    echo 'metadata:'
    echo '  name: kubeadm-config'
    kubectl -n kube-system get cm kubeadm-config -o jsonpath='{.data.ClusterConfiguration}' --kubeconfig /etc/kubernetes/admin.conf
  register: command_output

- name: Write the command output to a file
  copy:
    content: "{{ command_output.stdout }}"
    dest: /etc/kubernetes/kubeadm-config-ClusterConfiguration-dump.yaml

- name: Generate patch file from template
  template:
    src: patch-ClusterConfiguration.yml.j2
    dest: /etc/kubernetes/kubeadm-config-ClusterConfiguration-patch.yaml

# TODO copy kustomization.yaml and openapi json file to the node

# TODO generate final config with kustomize and apply the CM with kubectl (the CM should have the ClusterConfiguration key)

# TODO init components to regenerate static manifests