- name: Renew certificates
  command: "{{ item }}"
  with_items:
    - "kubeadm certs renew admin.conf"
    - "kubeadm certs renew apiserver"
    - "kubeadm certs renew apiserver-kubelet-client"
    - "kubeadm certs renew controller-manager.conf"
    - "kubeadm certs renew front-proxy-client"
    - "kubeadm certs renew scheduler.conf"

- name: Renew `super-admin.conf` certificate
  command: "kubeadm certs renew super-admin.conf"
  when: kubernetes_version is version('1.29.0', 'ge', version_type='semver')

- name: Upgrade kubernetes master with kubeadm (legacy)
  command: kubeadm upgrade apply --config /etc/kubernetes/kubeadm.yml -y
  when: kubernetes_version is version('1.30.0', 'lt', version_type='semver')

- name: Ensuring kubeadm-upgrade-config.yml config file is present on machine
  template:
    src: kubeadm-upgrade-config.yml.j2
    dest: "{{ kubeadm_upgrade_config_file }}"
  when: kubernetes_version is version('1.30.0', 'ge', version_type='semver')

- name: Upgrade kubernetes master with kubeadm
  command: kubeadm upgrade apply --config /etc/kubernetes/kubeadm-upgrade-config.yml
  when: kubernetes_version is version('1.30.0', 'ge', version_type='semver')
