- name: Upgrade Control Plane
  hosts: master
  serial: 1
  become: true
  tasks:
  
  - name: Upgrade etcd
    include_role:
      name: etcd
    tags:
    - kubeadm-upgrade

  - name: Upgrade control-plane
    block:
    - include_role:
        name: kube-node-common
    - include_role:
        name: kube-control-plane
    vars:
      skip_kubelet_upgrade: true
      upgrade: true
    tags:
    - kubeadm-upgrade

  - name: Kubelet and Containerd upgrade
    block:
    - include_role:
        name: kube-node-common
    - include_role:
        name: containerd
    vars:
      skip_kubelet_upgrade: false
    tags:
    - package-upgrade