- name: Upgrade Worker Nodes
  hosts: nodes
  serial: "{{ serial_number | default(1) }}"
  become: true
  tasks:

  - name: Kubernetes node preparation
    block:
    - include_role:
        name: kube-node-common
    vars:
      skip_kubelet_upgrade: true
    tags:
    - kube-node-common

  - name: Kubernetes drain
    block:
    - name: Get node name
      set_fact:
        node_name: "{{ kubernetes_hostname }}"
    - name: Drain node
      delegate_to: localhost
      shell: "kubectl drain --grace-period=60 --timeout=360s --force --ignore-daemonsets --delete-local-data {{ node_name }} --kubeconfig={{ kubernetes_kubeconfig_path }}admin.conf"
  
  - name: Kubernetes kubeadm upgrade node
    shell: "kubeadm upgrade node"

  - name: Kubelet and Containerd upgrade
    block:
    - include_role:
        name: kube-node-common
    - include_role:
        name: containerd
    vars:
      skip_kubelet_upgrade: false
    tags:
    - kube-node-common
    - containerd

  - name: Kubernetes uncordon
    block:
    - name: Get node name
      set_fact:
        node_name: "{{ kubernetes_hostname }}"
    - name: Uncordon node
      delegate_to: localhost
      shell: "sleep 60 && kubectl uncordon {{ node_name }} --kubeconfig={{ kubernetes_kubeconfig_path }}admin.conf"
