- name: Ensuring the kubelet-config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ kubelet_config_path }}/patches/"
    - "{{ kubelet_config_path }}/backups/"

- name: Set timestamp
  ansible.builtin.set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    mode: '0644'

- name: Backup current kubelet configuration file
  ansible.builtin.copy:
    src: /var/lib/kubelet/config.yaml
    dest: "{{ kubelet_config_path }}/backups/kubelet-config-backup-{{ timestamp }}.yaml"
    remote_src: true
    mode: '0644'

# Since worker nodes need kubeconfig
# we fetch it from a control plane node.
- name: Read kubeconfig from control plane node
  ansible.builtin.slurp:
    src: /etc/kubernetes/admin.conf
  register: admin_conf
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Set kubeconfig as fact
  ansible.builtin.set_fact:
    k8s_admin_conf: "{{ admin_conf['content'] | b64decode }}"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Generate patches file from template
  ansible.builtin.template:
    src: KubeletConfiguration.yml.j2
    dest: "{{ kubelet_config_path }}/patches/kubeletconfiguration.yaml"
    mode: '0644'
  notify: Apply kubelet-config patches
