- name: Ensuring the kubelet-config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ kubelet_config_path }}/patches/"
    - "{{ kubelet_config_path }}/backups/"

- name: Set timestamp
  ansible.builtin.set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    mode: '0644'

- name: Backup current kubelet configuration file
  ansible.builtin.copy:
    src: /var/lib/kubelet/config.yaml
    dest: "{{ kubelet_config_path }}/backups/kubelet-config-backup-{{ timestamp }}.yaml"
    remote_src: true
    mode: '0644'

- name: Generate patches file from template
  ansible.builtin.template:
    src: KubeletConfiguration.yml.j2
    dest: "{{ kubelet_config_path }}/patches/kubeletconfiguration.yaml"
    mode: '0644'
  notify: Apply kubelet-config patches
