---

- name: Remove deprecated Kubernetes YUM repository
  yum_repository:
    name: "{{ kubernetes_repo_deprecated['name'] }}"
    file: "{{ kubernetes_repo_deprecated['name'] }}"
    description: "{{ kubernetes_repo_deprecated['name'] }}"
    baseurl: "{{ kubernetes_repo_deprecated['yum_repo'] }}"
    gpgkey: "{{ kubernetes_repo_deprecated['yum_gpg_key'] }}"
    gpgcheck: "{{ kubernetes_repo_deprecated['yum_gpg_key_check'] }}"
    repo_gpgcheck: "yes"
    state: absent
  notify: Clean yum cache

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Search for yum-plugin-versionlock
  yum:
    list: yum-plugin-versionlock
  register: package_list

- name: Install yum-plugin-versionlock
  yum:
    name: yum-plugin-versionlock
    state: latest
  when: 'package_list.results | length != 0'

- name: Search for yum-versionlock
  yum:
    list: yum-versionlock
  register: package_list

- name: Install yum-versionlock
  yum:
    name: yum-versionlock
    state: latest
  when: 'package_list.results | length != 0'

- name: Add Kubernetes YUM repository
  yum_repository:
    name: "{{ dependencies[kubernetes_version].yum.name }}"
    file: "{{ dependencies[kubernetes_version].yum.name }}"
    description: "{{ dependencies[kubernetes_version].yum.name }}"
    baseurl: "{{ dependencies[kubernetes_version].yum.repo }}"
    gpgkey: "{{ dependencies[kubernetes_version].yum.gpg_key }}"
    gpgcheck: "{{ dependencies[kubernetes_version].yum.gpg_key_check }}"
    repo_gpgcheck: "{{ dependencies[kubernetes_version].yum.repo_gpg_check }}"
    state: present
  notify: Clean yum cache