apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  serviceName: registry
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.7.1
        env:
        - name: REGISTRY_HTTP_ADDR
          value: "0.0.0.0:5000"
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 5000
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
  volumeClaimTemplates:
  - metadata:
      name: registry-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 5000
    targetPort: http
  selector:
    app: registry
