---

- name: Clean yum cache
  command: /usr/bin/yum clean all
  args:
    warn: false

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  listen: Restart docker

- name: Restart journald
  systemd:
    name: systemd-journald
    state: restarted
  listen: Restart journald

- name: Systemctl restart # systemd loads service
  service:
    name: "systemd-modules-load.service"
    state: "restarted"
  changed_when: false
  failed_when: false

- name: Sysctl reload  # no reboot
  command: sysctl --system
  changed_when: false
  failed_when: false