# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
- name: Fetching certificates from etcd
  run_once: true
  delegate_to: "{{ groups.etcd[0] }}"
  ansible.builtin.fetch:
    src: "{{ etcd_certs_dir }}/{{ item }}"
    dest: "/tmp/etcd-certs/"
    flat: true
  with_items: "{{ etcd_certs }}"

- name: Copying certificates to control plane nodes
  run_once: true
  ansible.builtin.copy:
    src: "/tmp/etcd-certs/{{ item[1] | basename }}"
    dest: "{{ etcd_certs_dir }}/{{ item[1] }}"
    owner: root
    group: root
    mode: '0640'
  loop: "{{ groups['master'] | product(etcd_certs) | list }}"
  loop_control:
    loop_var: item
  delegate_to: "{{ item[0] }}"

- name: Cleaning up temporary certificates
  run_once: true
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: /tmp/etcd-certs
    state: absent
