# - name: getting etcd and role dependencies
#   apt:
#     name:
#       - tar
#       - git
#       - curl
#     state: present

- name: Making sure directories are present
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{ etcd_config_dir }}"
    - "{{ etcd_data_dir }}"
    - "{{ etcd_certs_dir }}"

- name: Generating TLS certificates
  import_tasks: tls.yml

- name: Installing and configuring etcd
  import_tasks: install.yml

- name: Enabling and starting etcd
  systemd:
    name: etcd
    daemon_reload: yes
    enabled: yes
    state: started

- name: Renewal etcd certificates
  import_tasks: renewal.yml
  when: upgrade

- name: Distribute etcd certificates from etcd to control plane nodes
  import_tasks: distribute.yml
  when: not etcd_on_control_plane
