---

- name: Making sure the kubeadm-etcd file is on the instance
  template:
    src: kubeadm-etcd.yml.j2
    dest: /etc/etcd/kubeadm-etcd.yml

- name: Generating etcd certificates (server, peer, client)
  shell: "kubeadm init phase certs {{ item }} --config=/etc/etcd/kubeadm-etcd.yml"
  with_items:
    - etcd-healthcheck-client
    - etcd-peer
    - etcd-server
    - apiserver-etcd-client
