---

- name: Ensuring kubeadm.yml config file is present on machine
  template:
    src: kubeadm.yml.j2
    dest: "{{ kubeadm_config_file }}"

- name: Check that the /etc/kubernetes/kubelet.conf exists on nodes
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: node_kubelet_conf

- name: Running kubeadm on the nodes
  command: "kubeadm join --config {{ kubeadm_config_file }}"
  when:
    - not node_kubelet_conf.stat.exists

- name: Check if kubelet config file exists
  ansible.builtin.stat:
    path: /var/lib/kubelet/config.yaml
  register: kubelet_config_file

# Needed because in cases of joining new nodes, at the first run the config.yaml
# is not set by the kubeletconfiguration but is read from the configmap, so
# the node has a different configuration from the other nodes.
- name: Reconfigure kubelet
  ansible.builtin.include_tasks: reconfigure-kubelet.yml
  when: kubelet_config_file.stat.exists
