apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
data:
  vsphere.conf: |-
    # Global properties in this section will be used for all specified vCenters unless overriden in VirtualCenter section.
    global:
      port: 443
      # set insecureFlag to true if the vCenter uses a self-signed cert
      insecureFlag: true
      # settings for using k8s secret
      secretName: cpi-global-secret
      secretNamespace: kube-system

    # vcenter section
    vcenter:
      tenant-finance:
        server: 1.1.1.1
        datacenters:
          - finanace
      tenant-hr:
        server: 192.168.0.1
        datacenters:
          - hrwest
          - hreast
      tenant-engineering:
        server: 10.0.0.1
        datacenters:
          - engineering
        secretName: cpi-engineering-secret
        secretNamespace: kube-system

    # labels for regions and zones
    labels:
      region: k8s-region
      zone: k8s-zone