---

- name: reload haproxy
  systemd:
    name: haproxy
    state: reloaded
  listen: reload haproxy

- name: reload keepalived
  systemd:
    name: keepalived
    state: reloaded
  listen: reload keepalived
