---
- name: Restart HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
  listen: restart haproxy

- name: Reload HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
  listen: reload haproxy

- name: Reload keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: reloaded
  listen: reload keepalived
