---
etcd_name: "{{ inventory_hostname }}"
# check compatibility on this link https://github.com/kubernetes/kubernetes/blob/v1.32.3/cmd/kubeadm/app/constants/constants.go (change the version accordingly)
etcd_version: v3.5.16
etcd_download_url: https://storage.googleapis.com/etcd
etcd_data_dir: /var/lib/etcd
etcd_binary_dir: /usr/local/bin
etcd_config_dir: /etc/etcd
etcd_certs_dir: /etc/etcd/pki
etcd_address: "{{ ansible_default_ipv4.address }}"
etcd_initial_cluster: "https://localhost:2380"
etcd_initial_cluster_state: "new"
etcd_client_address: 127.0.0.1
etcd_certs:
  - etcd/ca.crt
  - apiserver-etcd-client.crt
  - apiserver-etcd-client.key
etcd_on_control_plane: true
etcd_upgrade: false

