---

- name: Update APT cache
  apt:
    update_cache: true
  changed_when: false

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: Import Docker APT public key
  apt_key:
    id: "{{ docker_repo['apt_gpg_key_id'] }}"
    url: "{{ docker_repo['apt_gpg_key'] }}"
    state: present

- name: Add Docker APT repository
  apt_repository:
    filename: "{{ docker_repo['name'] }}"
    repo: "{{ docker_repo['apt_repo'] }}"
    state: present

- name: Update APT cache
  apt:
    update_cache: true
  changed_when: false
