apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  labels:
    app: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccount: dex
      containers:
      - name: dex
        env:
          - name: KUBERNETES_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: ghcr.io/dexidp/dex:v2.30.0
        command:
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yml
        ports:
        - name: http
          containerPort: 5556
        - name: metrics
          containerPort: 5558
        readinessProbe:
            httpGet:
              path: "/healthz"
              port: 5556
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
      volumes:
      - name: config
        secret:
          secretName: dex
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  labels:
    app: dex
spec:
  ports:
  - name: http
    port: 5556
    targetPort: http
  - name: metrics
    port: 5558
    targetPort: metrics
  selector:
    app: dex
