- name: Kill all running containers
  shell: "docker ps -q | xargs -r docker kill"

- name: Delete all stopped containers
  shell: "docker ps -a -q | xargs -r docker rm"

- name: Delete all images
  shell: "docker images -q | xargs -r docker rmi"

- name: Docker service stop # systemd loads service
  service:
    name: "docker.service"
    state: "stopped"
  changed_when: false
  failed_when: false

- name: Remove Docker
  package:
    name: "docker-ce"
    state: absent

- name: Remove Docker
  package:
    name: "docker-ce-cli"
    state: absent

- name: Delete docker folder
  file:
    state: absent
    path: "/var/lib/docker"

